server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native # Kích hoạt profile native để đọc local
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo